In [47]:
import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [48]:
df = pd.read_csv(r"C:\Projects\python\Machine Learning\Fake news detection\archive\data.csv")

df.shape
df.head()

,URLs,Headline,Body,Label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",1
2,https://www.nytimes.com/2017/10/09/us/politics...,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1
3,https://www.reuters.com/article/us-mexico-oil-...,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,1
4,http://www.cnn.com/videos/cnnmoney/2017/10/08/...,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",1

In [49]:
labels = df.Label
labels.head(100)

0     1
1     1
2     1
3     1
4     1
     ..
95    0
96    0
97    1
98    0
99    1
Name: Label, Length: 100, dtype: int64

In [50]:
#Get rid of NaN values
df = df.dropna()

#Replace 0 and 1 with True and Fake
df['Label'] = df['Label'].replace({
    0: "REAL",
    1: "FAKE"
})

x = df['Body']
y = df['Label']

print("x shape:", x.shape)
print("y shape:", y.shape)

df.head(20)

x shape: (3988,)
y shape: (3988,)

,URLs,Headline,Body,Label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,FAKE
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",FAKE
2,https://www.nytimes.com/2017/10/09/us/politics...,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,FAKE
3,https://www.reuters.com/article/us-mexico-oil-...,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,FAKE
4,http://www.cnn.com/videos/cnnmoney/2017/10/08/...,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",FAKE
5,http://beforeitsnews.com/sports/2017/09/jetnat...,JetNation FanDuel League; Week 4,JetNation FanDuel League; Week 4\n% of readers...,REAL
6,https://www.nytimes.com/2017/10/10/us/politics...,Kansas Tried a Tax Plan Similar to Trump’s. It...,"In 2012, Kansas lawmakers, led by Gov. Sam Bro...",FAKE
7,https://www.reuters.com/article/us-india-cenba...,"India RBI chief: growth important, but not at ...",The Reserve Bank of India (RBI) Governor Urjit...,FAKE
8,https://www.reuters.com/article/us-climatechan...,EPA chief to sign rule on Clean Power Plan exi...,"Scott Pruitt, Administrator of the U.S. Enviro...",FAKE
9,https://www.reuters.com/article/us-air-berlin-...,Talks on sale of Air Berlin planes to easyJet ...,FILE PHOTO - An Air Berlin sign is seen at an ...,FAKE
10,https://www.activistpost.com/2017/09/u-s-presi...,U.S. President Donald Trump Quietly Signs Law ...,By Aaron Kesel\nAs former White House chief of...,REAL
11,http://beforeitsnews.com/sports/2017/10/2017-f...,2017 Fantasy Football Team Defense Rankings - ...,2017 Fantasy Football Team Defense Rankings – ...,REAL
12,http://beforeitsnews.com/sports/2017/09/just-s...,Just Shut Up & Play Some Damn Baseball!!,Just Shut Up & Play Some Damn Baseball!!\n(Bef...,REAL
13,https://www.reuters.com/article/us-deloitte-cy...,Deloitte cyber attack affected up to 350 clien...,FILE PHOTO: The Deloitte Company logo is seen ...,FAKE
14,http://beforeitsnews.com/sports/2017/10/107-ch...,"10/7: Chuck Axed; HBD Brickyard, Adam, Moonlig...",A Potato Battery Can Light up a Room for Over ...,REAL
15,https://www.nytimes.com/2017/10/04/us/las-vega...,Gunman’s Girlfriend Said She Didn’t Know He Pl...,• The authorities found evidence that the gunm...,FAKE
16,https://www.nytimes.com/2017/10/04/us/marilou-...,"Marilou Danley, Gunman’s Girlfriend, Says She ...","The statement, which was read by her lawyer, M...",FAKE
17,https://www.nytimes.com/video/us/politics/1000...,Trump’s Immigration Rhetoric Echoes a Bitter F...,"In bold documentary style, Retro Report looks ...",FAKE
18,http://beforeitsnews.com/u-s-politics/2017/10/...,Trump Bemoans ‘Little Appreciation’ As San Jua...,Red Flag Warning: These California Wildfires A...,REAL
19,http://beforeitsnews.com/u-s-politics/2017/10/...,"In Meeting With Military, Trump Talks Of 'Calm...","In Meeting With Military, Trump Talks Of 'Calm...",REAL

In [51]:
#Split the dataset
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=7)

In [52]:
#Initialize a TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

#Fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(x_train)
tfidf_test = tfidf_vectorizer.transform(x_test)

In [53]:
#Initialize a PassiveAggressiveClassifier

pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

#Predict on the test set and calculate accuracy
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100, 2)}%")

Accuracy: 99.25%

In [54]:
#Build confusion matrix
confusion_matrix(y_test, y_pred, labels=['REAL', 'FAKE'])

array([[404,   5],
       [  1, 388]])